### ISSUE TITLE
Spectrum does not show after load unless I press another button

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#31]
It takes a long time (30 secs?) to load the very simple test spectrum provided by @nmearl into `pyfocal` GUI. I can't even imagine how long it will take to load multi-dimensional FITS spectra.

Is this just me?

**Comment by pllim** [comment]
In addition, the test spectrum gives the following FITS warning:
```
WARNING: FITSFixedWarning: The WCS transformation has more axes (1) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: The WCS transformation has more axes (1) than the image it is associated with (0)
WARNING: UnitsWarning: 'erg/cm^2/s/Angstrom' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING:astropy:UnitsWarning: 'erg/cm^2/s/Angstrom' contains multiple slashes, which is discouraged by the FITS standard
WARNING: UnitsWarning: The unit 'Angstrom' has been deprecated in the FITS standard. Suggested: 10**-1 nm. [astropy.units.format.utils]
WARNING:astropy:UnitsWarning: The unit 'Angstrom' has been deprecated in the FITS standard. Suggested: 10**-1 nm.
```

**Comment by nmearl** [comment]
That's very strange. It's quite fast for me. What's your current environment (python 2/3? PyQt/PySide?)

**Comment by pllim** [comment]
Anaconda Python 2. PyQt4.

**Comment by pllim** [comment]
Okay,  never mind. I tried again and realized that it does not display unless I explicitly click the left-most icon under "Data" sub-window. Is this behavior intentional?

**Comment by nmearl** [comment]
> Okay, never mind. I tried again and realized that it does not display unless I explicitly click the left-most icon under "Data" sub-window. Is this behavior intentional? 

Yes. That could be made more obvious. This was the behavior decided upon with the last SpecView sprint. It does not plot the data by default.

Also, perhaps I should start on some quickstart documentation to make that clear to users...

**Comment by pllim** [comment]
Ah, okay. Yes, the behavior is not very intuitive to me, so some kind of doc would be nice. Thanks!

**Comment by ibusko** [comment]
I would like to chime in on this. I might have missed the discussion (on the past specview sprint) on default behavior after loading the spectrum. I faced a similar dilema when working with the older (*much* older...) Java specview. Users usually get confused when the default behavior when loading a spectrum is different than just "plot it immediately". And there are circumstances when that behavior is not to be desired. One case is when using wildcards or lists of input file names. Another case is when loading from Virtual Observatory spectrum data servers. These actions may load hundreds of spectra at once in the app data memory. Which one to display? 

Some specific, instrument or science-dependent, use cases had default actions to apply, such as "load these N spectra and combine then into a single stretch of data, then plot".  But in the generic case of multiple spectra input at once, I think the correct default approach is to do what the current (and the old Java) specview does, that is, do nothing apart from listing somewhere (as in the Data window) the names of the data loaded. The Java specview resorts to the immediate plot action only when the data that is input can be unambiguously cast as a single spectrum. For example, a FITS file containing an echelle spectrum can be seen as a collection of spectra, or as a single spectrum. The Java specview will handle it based on rules contained in instrument-specific reader classes. In that app, for most instruments that create data of this type the user can opt for either action: do not plot, or combine according to instrument-specific rules, and plot immediately. VO data cannot be combined because there is no known set of universal combination rules. Unless all the VO data that were downloaded are from a single instrument. Or from a single astronomical source? And so on. The problem can be as complex as we want, I am afraid. At some point we should draw the proverbial line in the sand.

I think for a first release of specview, the current behavior is fine. Especially if we can make the "Create layer" (or "Plot" ?) button more conspicuous or obvious. In the future it might be desirable (or not) to enrich that basic behavior.

**Comment by pllim** [comment]
That is fine, as long as it is made very clear that user has to push some button to plot the data.

Although in the future, the interface might benefit from some kind of user configuration. For example, user can have a config file (say, in `~/.pyfocal`) that overrides this default behavior by telling `pyfocal` to auto display if less than X number of spectra are being loaded, and whether to plot them all in the same place or separately. Just a thought.

**Comment by pllim** [comment]
Documentation added about pressing this button.
