### ISSUE TITLE
ModelLayer should subclass Layer

### ISSUE THREAD

**Issue by pllim** [nmearl/pyfocal#52]
`ModelLayer` should subclass `Layer` in `core/data.py`. It does not make sense otherwise.

**Comment by pllim** [comment]
Unless @ibusko has reason not to do so, since he is working on the modeling portion of Pyfocal.

**Comment by nmearl** [comment]
I have a local branch that deals with this, but `ModelLayer` should not be a subclass of `Layer`. There should be a `BaseLayer` class, and both `Layer` and `ModelLayer` should subclass it. `Layer` and `ModelLayer` should not be thought of as inheritable objects.

Further, `Layer` needs to be renamed to `DataLayer` for clarity.

@ibusko, don't worry about implementing this. I've already got something cooking.

**Comment by pllim** [comment]
In that case, the docstring for `Layer` is misleading.

**Comment by nmearl** [comment]
How so? I'd say the doc string for `ModelLayer` is misleading.

But looking over this branch again with fresh eyes and considering how the objects have changed since implementing (e.g. the doc string for `ModelLayer` still talks about using `Data` objects directly), I do actually think that the `ModelLayer` should be a subclass of `Layer`.

I'll make the changes and push the branch. Thanks for making this a ticket, I would have forgotten otherwise. :astonished:

**Comment by pllim** [comment]
Oh. I just updated the doc again in #53 but then I saw your comment. Anyways, we can always update the doc again when your subclassing is merged. I hope all my changes won't be too painful for you to rebase. Let me know if I should stay away from modifying certain files. Thanks!

**Comment by nmearl** [comment]
Done in #97.
