### ISSUE TITLE
Is there a way to remove a model?

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#66]
I see the option to "Add" a model...which puts it in the list of models. I don't see an option to remove a model from this list, and it's unclear to me what it is doing when I do a fit if I have two models there and no arithmetic behavior specified.

**Comment by nmearl** [comment]
We talked about this today at the tag-up. It exists as a context menu option, but the context menus are not currently in the GUI.

**Comment by ibusko** [comment]
@hcferguson :  if no arithmetic behavior is specified, the compound model builder defaults to adding together all models in the list.

I was thinking, is the "Add" button necessary? We could have no Add button, and its callback function connected instead to the 'select' action in the drop down selector. That would free some real estate on screen.

**Comment by hcferguson** [comment]
@ibusko I like that suggestion. I think "Add" also can be confusing when we are also allowing model arithmetic. 

I might also suggest that "Create" could be renamed "Initialize" to make it a bit clearer what it's doing?

**Comment by nmearl** [comment]
@ibusko @hcferguson This is how we had it in SpecView. I'm not sure I agree. The problem before was that a user, after having selected an item from the drop down, can accidentally use their scroll wheel while the widget is still active. Every change of the item will result in that model being added to the list.

This can be circumvented by manually blocking signaling from the widget, but I don't think it's worth the effort currently.

> I might also suggest that "Create" could be renamed "Initialize" to make it a bit clearer what it's doing?

Sure, if you think that's more appropriate. "Create" was used because you're, in the back end, "creating" a new layer for the model to live in.

**Comment by hcferguson** [comment]
@nmearl @ibusko Then I think "Select" instead of "Add" makes it clearer. 
As for "Create"....maybe "Create Model Layer," if it fits?

**Comment by nmearl** [comment]
> @nmearl @ibusko Then I think "Select" instead of "Add" makes it clearer.
As for "Create"....maybe "Create Model Layer," if it fits? 

Tweaked in 17a2479d822fc4c9eb520ada7bd7af7606eb23ad.

Going to close this, and point people to #102 for tracking removing of objects from the gui.
